


export const ALL_STEPS = [
  { id: "basic", title: "Basic" },
  { id: "hero", title: "Hero" },
  { id: "bhk", title: "BHK" },
  { id: "amenities", title: "Amenities" },
  { id: "gallery", title: "Gallery" },
  { id: "about", title: "About" },
  { id: "location", title: "Location" },
  { id: "propertyProfiles", title: "Profiles" },
  { id: "seo", title: "SEO" },
];  


export const STEP_META = [
  { icon: "🏷️", desc: "Property name, address & location basics" },
  { icon: "🖼️", desc: "Hero banner, tagline & branding" },
  { icon: "🏠", desc: "BHK types, sizes & pricing" },
  { icon: "✨", desc: "Features, specs & lead info" },
  { icon: "📸", desc: "Property gallery images" },
  { icon: "📝", desc: "About section content & image" },
  { icon: "📍", desc: "Map coordinates & nearby places" },
  { icon: "📊", desc: "Towers, RERA, banks & documents" },
  { icon: "🔍", desc: "Meta title, description & keywords" },
];

export const INITIAL_PAYLOAD = {
  title: "",
  logo: "",
  description: "",
  heroImage: null,
  heroTagline: "",
  heroSubTagline: "",
  heroDescription: "",
  color: "",
  createdBy: "",
  mapEmbedUrl: "",
  metaTitle: "",
  metaDescription: "",
  metaKeywords: "",
  address: "",
  city: "",
  location: { type: "Point", coordinates: ["", ""] },
  state: "",
  locality: "",
  currency: "INR",
  status: "active",
  isFeatured: true,
  sqftRange: { min: "", max: "" },
  possessionDate: "",
  totalTowers: "",
  totalFloors: "",
  projectArea: "",
  totalUnits: "",
  availableUnits: "",
  reraNumber: "",
  banksApproved: [],
  brochure: null,
  specifications: [],
  gallerySummary: [],
  galleryFiles: [],
  aboutSummary: [],
  aboutImage: null,
  bhkSummary: [],
  amenities: [],
  nearbyPlaces: [],
  leads: [],
  relatedProjects: [],
  youtubeVideos: [],
};
