/* eslint-disable no-unused-vars -- icon components are also rendered from data-driven tuples */
import { createElement, useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowRight, BadgeCheck, Building2, CalendarDays, Check, ChevronDown, CircleDot, Clock3, Download, Eye, Gauge, Globe2, ListFilter, LoaderCircle, MapPin, Monitor, MousePointer2, Pause, Phone, Play, RefreshCw, Search, Send, ShieldCheck, Smartphone, Target, UserCheck, UserRound, Users, Wifi } from "lucide-react";
import { apiClient } from "../../api/apiClient";
import { getAllUsers } from "../../features/user/userService";

const roles = ["user", "builder", "builder_staff", "agent"];
const title = (value = "") => String(value || "Unknown").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
const initials = (name = "User") => name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
const maskPhone = (phone = "") => phone ? `${phone.slice(0, 5)}••••${phone.slice(-2)}` : "Phone unavailable";
const seed = (value = "propenu") => [...String(value)].reduce((sum, char) => sum + char.charCodeAt(0), 0);
const demoEvents = [
  ["10:29:23", "OTP verification failed", "Site visit / OTP", "—", "Attempt 1", "risk"], ["10:28:45", "Form started", "Green Acres / Enquire", "38s", "Site visit"], ["10:28:05", "WhatsApp clicked", "Green Acres · Plot 145", "20s", "Assisted"], ["10:27:00", "Price calculator used", "Green Acres · Plot 145", "1m 10s", "Budget ₹48L"], ["10:25:50", "Brochure downloaded", "Green Acres · Plot 145", "45s", "PDF"], ["10:23:59", "Gallery viewed", "Green Acres · Plot 145", "55s", "12 images"], ["10:23:04", "Property viewed", "Green Acres · Plot 145", "2m 38s", "View #3"], ["10:20:16", "Map opened", "Search results", "30s", "West Hyderabad"], ["10:18:31", "Filter applied", "Plot search", "1m 21s", "₹35–55L · 200–300 sq yd"], ["10:17:19", "Search performed", "Plot search", "1m 12s", "Plots in West Hyderabad"],
];
const stages = [["Acquisition", "Google Organic", "Campaign / plots", 100], ["Sign Up", "Registered", "24 sessions", 100], ["Search", "West Hyderabad", "₹35–55L", 92], ["Explore", "3 properties", "8m 16s", 88], ["Compare", "Plots 145 + 78", "3 comparisons", 50], ["Enquire", "Site visit form", "WhatsApp + form", 17], ["Stopped", "OTP verification", "Idle for 6m 18s", 4, true]];
const properties = [["Green Acres · Plot 145", 96, 9, "8m 16s", "High"], ["Riverfront · Plot 78", 83, 6, "4m 05s", "Medium"], ["Hill View · Plot 203", 72, 4, "2m 10s", "Medium"], ["Sunrise County · Plot 54", 61, 2, "1m 45s", "Low"]];

function Avatar({ user, size = "h-10 w-10" }) { return user?.profileImage ? <img src={user.profileImage} alt="" className={`${size} rounded-full object-cover ring-2 ring-white`}/> : <div className={`${size} grid place-items-center rounded-full bg-gradient-to-br from-emerald-500 to-emerald-700 font-black text-white ring-2 ring-white`}>{initials(user?.name)}</div>; }
function Chip({ children, tone = "green" }) { const tones = { green: "border-emerald-200 bg-emerald-50 text-emerald-700", orange: "border-orange-200 bg-orange-50 text-orange-700", blue: "border-blue-200 bg-blue-50 text-blue-700", slate: "border-slate-200 bg-slate-50 text-slate-600" }; return <span className={`inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[8px] font-bold ${tones[tone]}`}>{children}</span>; }
function Panel({ title: heading, subtitle, children, action, className = "" }) { return <section className={`uj-panel ${className}`}><header className="flex min-h-11 items-center justify-between border-b border-slate-100 px-3 py-2"><div><h2 className="text-[11px] font-black text-slate-800">{heading}</h2>{subtitle && <p className="text-[8px] text-slate-400">{subtitle}</p>}</div>{action}</header>{children}</section>; }
function Metric({ icon, label, value, suffix, change, tone = "green" }) { const colors = { green: "text-emerald-600", blue: "text-blue-600", orange: "text-orange-600", violet: "text-violet-600" }; return <div className="min-w-0 border-r border-slate-100 px-3 py-2 last:border-r-0"><div className="flex items-center gap-1 text-[8px] font-bold text-slate-500">{createElement(icon, { size: 11, className: colors[tone] })}{label}</div><div className="mt-1 flex items-end gap-1"><strong className="text-xl leading-none text-slate-900">{value}</strong>{suffix && <span className="text-[8px] text-slate-500">{suffix}</span>}{change && <span className="ml-auto text-[8px] font-bold text-emerald-600">↗ {change}</span>}</div></div>; }
function preview(user) { const n = seed(user?._id || user?.email || user?.name); return { isPreview: true, online: true, journeyScore: 82 + n % 12, buyingIntent: 88 + n % 9, sessions: 16 + n % 13, engagedMinutes: 260 + n % 100, propertiesViewed: 27 + n % 21, shortlisted: 5 + n % 6, leads: 2 + n % 4, siteVisits: n % 3, events: demoEvents }; }

function JourneyMap() {
  const simple = [["Acquisition", "G", "Google Organic", "May 22, 10:14 AM", "Entry 100%"], ["Sign Up", "U", "Registered", "May 22, 10:16 AM", "24 sessions"], ["Search", "Q", "Plots in West Hyderabad", "May 22, 10:17 AM", "92% reached"], ["Explore", "F", "Filters Applied", "Rs35L - Rs55L", "88% reached"]];
  return <div className="uj-journey-canvas">
    <div className="uj-journey-legend"><span className="text-emerald-600">— Completed</span><span className="text-blue-500">— Exploring</span><span className="text-orange-500">— Friction / Drop-off</span><em>All times in IST</em></div>
    <div className="uj-journey-grid">
      {simple.map(([name, icon, detail, meta, reach], index) => <div className="uj-journey-node" key={name}><b>{name}</b><i>{icon}</i><strong>{detail}</strong><small>{meta}</small><span>{reach}</span>{index < simple.length - 1 && <ArrowRight className="uj-node-arrow" size={13}/>}</div>)}
      <div className="uj-property-branch"><b>Properties explored</b>{[["Green Acres", "Plot 145", "3 views · 2m 38s"], ["Riverfront", "Plot 78", "2 views · 1m 42s"], ["Hill View", "Plot 203", "1 view · 1m 05s"]].map(([name, plot, meta], index) => <div className={`uj-property-mini uj-property-${index}`} key={name}><span/><strong>{name}<small>{plot}</small></strong><em>{meta}</em></div>)}</div>
      <div className="uj-action-branch"><b>Compare</b><div><BadgeCheck size={13}/><span><strong>Compared 3 plots</strong><small>May 22, 10:23 AM</small></span></div><div><Download size={13}/><span><strong>3 brochures</strong><small>Downloaded</small></span></div></div>
      <div className="uj-action-branch"><b>Enquire</b><div><Gauge size={13}/><span><strong>Price calculator</strong><small>Used 2 times</small></span></div><div><Smartphone size={13}/><span><strong>WhatsApp click</strong><small>20 seconds</small></span></div><div><CalendarDays size={13}/><span><strong>Form started</strong><small>38 seconds</small></span></div></div>
      <div className="uj-stop-node"><b>STOPPED</b><AlertTriangle size={18}/><strong>Site visit OTP verification</strong><em>Idle for 6m 18s</em><small>10:35 AM</small></div>
    </div>
    <div className="uj-journey-totals">{[[24,"100%"],[24,"100%"],[22,"92%"],[21,"88%"],[12,"50%"],[7,"29%"],[1,"4%"]].map(([count,pct]) => <span key={`${count}-${pct}`}>{count} ({pct}) <ArrowRight size={10}/></span>)}</div>
    <div className="mt-2"><AttributionPath/></div>
  </div>;
}

function AttributionPath() {
  return <Panel title="Attribution Path" subtitle="First touch to assisted conversion"><div className="flex h-28 items-center justify-around px-3">{[["G","Google Organic","24 sessions"],["L","Landing Page","24 sessions"],["R","Returning Direct","12 sessions"],["W","WhatsApp","4 leads"]].map(([icon,label,meta],index) => <div className="relative text-center" key={label}><i className="mx-auto grid h-7 w-7 place-items-center rounded-full bg-emerald-50 text-[11px] font-black text-emerald-600">{icon}</i><b className="mt-1 block text-[8px]">{label}</b><small className="text-[7px] text-slate-400">{meta}</small>{index < 3 && <ArrowRight className="absolute -right-6 top-2 text-slate-400" size={12}/>}</div>)}</div></Panel>;
}

export default function LeadCaptureAnalytics() {
  const [users, setUsers] = useState([]), [selectedId, setSelectedId] = useState(""), [journey, setJourney] = useState(null);
  const [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [query, setQuery] = useState(""), [eventQuery, setEventQuery] = useState(""), [range, setRange] = useState("30"), [playing, setPlaying] = useState(false), [live, setLive] = useState(true), [toast, setToast] = useState("");
  const user = useMemo(() => users.find((item) => item._id === selectedId) || users[0], [selectedId, users]);
  const loadUsers = useCallback(async () => { setLoading(true); try { const result = await getAllUsers(); const payload = result?.data; const list = (Array.isArray(payload) ? payload : payload?.users || []).filter((item) => roles.includes(item.roleName)); setUsers(list); setSelectedId((current) => current || list[0]?._id || ""); } finally { setLoading(false); } }, []);
  const loadJourney = useCallback(async (person) => { if (!person) return; setRefreshing(true); try { const response = await apiClient.get(`/api/admin/user-journey/${person._id}`, { params: { days: range } }); setJourney({ ...preview(person), ...response?.data?.data, isPreview: false }); } catch { setJourney(preview(person)); } finally { setRefreshing(false); } }, [range]);
  useEffect(() => {
    // Initial synchronization with the existing admin user API.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadUsers();
  }, [loadUsers]);
  useEffect(() => {
    // Synchronize the selected user's activity stream.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (user) loadJourney(user);
  }, [user, loadJourney]);
  useEffect(() => { if (!live || !user) return undefined; const timer = window.setInterval(() => loadJourney(user), 30000); return () => window.clearInterval(timer); }, [live, loadJourney, user]);
  useEffect(() => { if (!toast) return undefined; const timer = window.setTimeout(() => setToast(""), 2600); return () => window.clearTimeout(timer); }, [toast]);
  const filteredUsers = useMemo(() => { const q = query.toLowerCase().trim(); return users.filter((item) => !q || [item.name, item.email, item.phone, item.city, item.state].some((value) => String(value || "").toLowerCase().includes(q))).slice(0, 8); }, [query, users]);
  const events = useMemo(() => (journey?.events || demoEvents).filter((row) => !eventQuery || row.join(" ").toLowerCase().includes(eventQuery.toLowerCase())), [eventQuery, journey]);
  const minutes = journey?.engagedMinutes || 318;
  if (loading) return <div className="grid min-h-[70vh] place-items-center"><LoaderCircle className="animate-spin text-emerald-600" size={34}/></div>;
  if (!user) return <div className="rounded-xl border bg-white p-10 text-center"><Users className="mx-auto text-slate-300"/><h1 className="mt-3 font-black">No trackable users found</h1></div>;
  const notify = setToast;
  return <div className="uj-page relative text-slate-900">
    {toast && <div className="uj-toast"><Check size={14}/>{toast}</div>}
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 pb-2"><div><h1 className="text-xl font-black tracking-tight">User Journey Intelligence</h1><p className="text-[9px] text-slate-500">Behavior, intent, friction and conversion tracing · First-party consented data</p></div><div className="flex items-center gap-2"><select value={range} onChange={(e) => setRange(e.target.value)} className="uj-control"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><button onClick={() => setLive((value) => !value)} className={`uj-control gap-2 ${live ? "text-emerald-700" : "text-slate-500"}`}><span className={`h-2 w-2 rounded-full ${live ? "animate-pulse bg-emerald-500" : "bg-slate-300"}`}/>{live ? "Live" : "Paused"}<ChevronDown size={12}/></button><button onClick={() => window.print()} className="uj-control"><Download size={13}/>Export</button><button onClick={() => loadJourney(user)} className="uj-icon-button"><RefreshCw size={14} className={refreshing ? "animate-spin" : ""}/></button></div></header>
    <section className="mt-2 grid items-center gap-2 rounded-xl border border-slate-200 bg-white p-2 shadow-sm xl:grid-cols-[280px_1fr_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={14}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search user, mobile or email" className="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-[10px] outline-none focus:border-emerald-500"/>{query && <div className="absolute z-30 mt-1 max-h-64 w-full overflow-auto rounded-lg border bg-white p-1 shadow-xl">{filteredUsers.map((item) => <button key={item._id} onClick={() => { setSelectedId(item._id); setQuery(""); }} className="flex w-full items-center gap-2 rounded-md p-2 text-left hover:bg-emerald-50"><Avatar user={item} size="h-7 w-7"/><span><strong className="block text-[9px]">{item.name}</strong><small className="text-[8px] text-slate-400">{item.email || item.phone}</small></span></button>)}</div>}</div><div className="flex min-w-0 flex-wrap items-center gap-2"><Avatar user={user}/><div className="mr-2 min-w-[130px]"><strong className="block truncate text-[12px]">{user.name || "Registered user"}</strong><span className="block truncate text-[8px] text-slate-500">{maskPhone(user.phone)} · {[user.city, user.state].filter(Boolean).join(", ")}</span></div><Chip tone="blue"><UserCheck size={11}/>{title(user.roleName)}</Chip><Chip><CircleDot size={10}/>Online now</Chip><Chip tone="orange"><Target size={10}/>High intent</Chip><Chip><BadgeCheck size={10}/>Verified</Chip><Chip><ShieldCheck size={10}/>Consent active</Chip></div><div className="flex gap-2"><button onClick={() => notify("Contact request opened")} className="uj-action-primary"><Phone size={13}/>Contact</button><button onClick={() => notify("User assigned to sales agent")} className="uj-action"><UserRound size={13}/>Assign agent</button><button onClick={() => notify("Follow-up task created")} className="uj-action"><CircleDot size={13}/>Create task</button></div></section>
    {journey?.isPreview && <div className="mt-2 flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-1.5 text-[9px] text-amber-800"><AlertTriangle size={12}/><strong>Preview behavior data:</strong> identity is live; journey data becomes live automatically when the tracking endpoint is connected.</div>}
    <section className="mt-2 grid grid-cols-2 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm sm:grid-cols-4 xl:grid-cols-9"><Metric icon={Gauge} label="Journey Score" value={journey?.journeyScore || 87} suffix="/100"/><Metric icon={Target} label="Buying Intent" value={journey?.buyingIntent || 92} suffix="High"/><Metric icon={Activity} label="Sessions" value={journey?.sessions || 24} change="26%" tone="blue"/><Metric icon={Clock3} label="Engaged Time" value={`${Math.floor(minutes / 60)}h ${minutes % 60}m`} change="18%"/><Metric icon={Eye} label="Properties Viewed" value={journey?.propertiesViewed || 43} change="34%"/><Metric icon={BadgeCheck} label="Shortlisted" value={journey?.shortlisted || 8} change="14%" tone="violet"/><Metric icon={Users} label="Leads" value={journey?.leads || 4} change="33%"/><Metric icon={CalendarDays} label="Site Visits" value={journey?.siteVisits || 1}/><Metric icon={Building2} label="Budget" value="₹48L" tone="orange"/></section>
    <section className="mt-2 grid gap-2 2xl:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-2">
      <Panel title="Live Journey Map" subtitle="Complete path, exploration branches and exact stopping point" action={<Chip><Wifi size={10}/>Streaming</Chip>}><JourneyMap/></Panel>
      <div className="grid gap-2 xl:grid-cols-[310px_minmax(0,1fr)_390px]"><Panel title="Session Replay & Heatmap" subtitle="Mobile · Chrome · Hyderabad"><div className="p-3"><div className="uj-replay"><div className="flex h-6 items-center justify-between border-b bg-white px-2 text-[7px]"><b className="text-emerald-700">PROPENU</b><span>Projects · Properties · Contact</span></div><div className="relative h-28 overflow-hidden bg-gradient-to-br from-emerald-100 via-lime-50 to-slate-100 p-3"><div className="h-16 rounded-md bg-[linear-gradient(135deg,#9dc28c,#4b7259)] shadow-inner"/><span className="uj-heat left-[34%] top-[35%]"/><span className="uj-heat left-[66%] top-[52%]"/><span className="uj-heat left-[50%] top-[74%]"/><strong className="absolute bottom-2 left-3 rounded bg-white/90 px-2 py-1 text-[8px]">Green Acres · Plot 145 · ₹46.5L</strong></div></div><div className="mt-3 flex items-center gap-3"><button onClick={() => setPlaying((value) => !value)} className="uj-icon-button">{playing ? <Pause size={13}/> : <Play size={13}/>}</button><div className="h-1 flex-1 overflow-hidden rounded bg-slate-100"><div className={`h-full w-3/4 bg-emerald-500 ${playing ? "uj-progress" : ""}`}/></div><span className="text-[8px]">10:28 / 15:42</span></div><div className="mt-3 flex justify-between text-center text-[8px]"><span><b className="block text-lg text-red-500">3</b>Rage clicks</span><span><b className="block text-lg text-blue-600">1</b>Dead click</span><span><b className="block text-lg text-slate-800">37</b>Clicks</span></div></div></Panel>
      <Panel title="Event Stream" subtitle="Live page, click and form activity" action={<ListFilter size={13} className="text-slate-400"/>}><div className="border-b p-2"><label className="relative"><Search size={11} className="absolute left-2 top-2 text-slate-400"/><input value={eventQuery} onChange={(e) => setEventQuery(e.target.value)} placeholder="Search events..." className="h-7 w-full rounded-md border pl-7 text-[8px] outline-none focus:border-emerald-500"/></label></div><div className="uj-table-scroll"><table className="w-full min-w-[560px] text-left text-[8px]"><thead><tr><th>Time</th><th>Event</th><th>Page / Entity</th><th>Duration</th><th>Metadata</th></tr></thead><tbody>{events.map((row) => <tr key={`${row[0]}-${row[1]}`}><td>{row[0]}</td><td className={row[5] === "risk" ? "font-bold text-red-600" : "font-semibold"}><span className={`mr-1 inline-block h-1.5 w-1.5 rounded-full ${row[5] === "risk" ? "bg-red-500" : "bg-emerald-500"}`}/>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td></tr>)}</tbody></table></div></Panel>
      <Panel title="Property Affinity Matrix" subtitle="Ranked by behavioral match score"><div className="uj-table-scroll"><table className="w-full text-left text-[8px]"><thead><tr><th>Property / Plot</th><th>Match</th><th>Views</th><th>Dwell</th><th>Status</th></tr></thead><tbody>{properties.map((item) => <tr key={item[0]}><td><div className="flex items-center gap-2"><span className="grid h-7 w-9 place-items-center rounded bg-emerald-100 text-emerald-700"><Building2 size={12}/></span><b>{item[0]}</b></div></td><td className="font-black text-emerald-600">{item[1]}%</td><td>{item[2]}</td><td>{item[3]}</td><td><Chip tone={item[4] === "High" ? "green" : "orange"}>{item[4]}</Chip></td></tr>)}</tbody></table></div></Panel></div>
      <div className="grid gap-2 lg:grid-cols-4"><Panel title="Multi-session Timeline" subtitle={`${journey?.sessions || 24} sessions · mobile and desktop`}><div className="p-3"><div className="uj-session-grid">{Array.from({ length: 32 }, (_, index) => <i key={index} className={index % 3 ? "bg-emerald-500" : "bg-blue-500"} style={{ left: `${4 + index * 2.9}%`, top: `${12 + (index * 37) % 78}%` }}/>)}</div><div className="mt-2 flex gap-3 text-[8px]"><span className="text-emerald-600">● Mobile 18</span><span className="text-blue-600">● Desktop 6</span></div></div></Panel><Panel title="Conversion Funnel" subtitle="End-to-end progression"><div className="flex h-32 items-end gap-1 p-3">{[["Reg",100],["Search",92],["View",88],["Short",33],["Lead",17],["Visit",4],["Book",0]].map(([name,pct]) => <div key={name} className="flex flex-1 flex-col items-center gap-1"><b className="text-[9px]">{pct}%</b><div className="w-full rounded-t bg-gradient-to-t from-emerald-100 to-emerald-400" style={{ height: `${Math.max(8, pct * .65)}px` }}/><small className="text-[7px] text-slate-500">{name}</small></div>)}</div></Panel><Panel title="Friction & Risk" subtitle="Signals requiring attention"><div className="space-y-2 p-3 text-[8px]">{[["OTP verification failed","High","orange"],["Price calculator repeated","Medium","orange"],["Form abandonment","Medium","orange"],["No fraud detected","Clear","green"]].map(([name,status,tone]) => <div className="flex items-center justify-between" key={name}><span>• {name}</span><Chip tone={tone}>{status}</Chip></div>)}</div></Panel><Panel title="Location Interest" subtitle="Hyderabad behavioral hotspots"><div className="relative h-32 overflow-hidden bg-[radial-gradient(circle_at_20%_40%,#dbeafe,transparent_18%),radial-gradient(circle_at_70%_60%,#d1fae5,transparent_22%),linear-gradient(135deg,#f8fafc,#e2e8f0)]"><span className="uj-map-dot left-[64%] top-[52%]"/><span className="uj-map-dot left-[35%] top-[62%]"/><span className="uj-map-dot left-[75%] top-[22%]"/><small className="absolute left-[58%] top-[67%]">Kokapet</small><small className="absolute left-[25%] top-[76%]">Shankarpally</small><small className="absolute left-[70%] top-[10%]">Mokila</small></div></Panel></div>
    </div><aside className="grid content-start gap-2 md:grid-cols-2 2xl:grid-cols-1"><Panel title="1. AI Journey Summary" subtitle="Behavioral intelligence"><ul className="space-y-2 p-3 text-[9px]">{["Returned 4 times in 7 days","Revisited Plot 145 three times","High price sensitivity","Used price calculator twice","Downloaded 3 brochures","Engaged through WhatsApp","OTP friction blocking visit"].map((item) => <li key={item} className="flex gap-2"><span className="mt-1 h-1.5 w-1.5 rounded-full bg-emerald-500"/>{item}</li>)}</ul></Panel><Panel title="2. Next Best Action" subtitle="91% confidence"><div className="space-y-3 p-3"><div className="rounded-lg bg-emerald-50 p-2 text-[9px]"><b>Recommended: Call within 10 min</b><p className="mt-1 text-slate-500">Resolve OTP friction while intent is high.</p></div><div className="flex items-center gap-2 rounded-lg border p-2"><Avatar user={{ name: "Rakesh Reddy" }} size="h-8 w-8"/><span className="text-[8px]"><b className="block">Rakesh Reddy</b>West Hyderabad sales</span></div><div className="grid grid-cols-2 gap-2"><button onClick={() => notify("Agent assigned and notified")} className="uj-action-primary"><Send size={11}/>Assign</button><button onClick={() => notify("WhatsApp assistance queued")} className="uj-action"><Smartphone size={11}/>WhatsApp</button></div></div></Panel><Panel title="3. Live Context" subtitle="Current user environment"><div className="space-y-2.5 p-3 text-[8px]">{[[Globe2,"Current URL","/projects/green-acres/plot-145"],[Monitor,"Device","Desktop · Chrome 124"],[MapPin,"Location",`${user.city || "Hyderabad"}, ${user.state || "Telangana"}`],[Wifi,"Network","Good · 4G/Wi-Fi"],[MousePointer2,"Last interaction","OTP resend · 6m ago"]].map(([Icon,label,value]) => <div className="flex gap-2" key={label}><Icon size={12} className="text-slate-400"/><span><b className="block text-slate-500">{label}</b><span className="break-all">{value}</span></span></div>)}</div></Panel><Panel title="Intent Signals" subtitle="Fit across buying dimensions"><div className="p-3"><div className="uj-radar"><span>Location Fit</span><span>Budget</span><span>Engagement</span><span>Urgency</span><span>Trust</span><div/></div></div></Panel></aside></section>
    <footer className="mt-2 flex flex-wrap items-center justify-center gap-3 rounded-lg border border-emerald-100 bg-emerald-50/70 px-3 py-2 text-[8px] text-emerald-800"><ShieldCheck size={13}/><b>Consent active</b><span>· PII masked</span><span>· Role-based access</span><span>· Audit logged</span><span>· Retention 90 days</span><span className="ml-auto flex items-center gap-1"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/>Live</span></footer>
  </div>;
}
