import { createElement, useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Building2, CalendarDays, ChevronRight, Clock3, Download, Filter, MapPin, RefreshCw, Search, ShieldCheck, UserCheck, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { apiClient } from "../../api/apiClient";
import { getAllProjectsAnalytics, getAllPropertiesAnalytics } from "../../features/property/propertyService";
import { getAllUsers } from "../../features/user/userService";

const fmt = (value) => Number(value || 0).toLocaleString("en-IN");
const clean = (value = "") => String(value || "Not specified").replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
const valid = (value) => value && !["unknown", "not specified", "n/a"].includes(String(value).toLowerCase());
const dayKey = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : date.toISOString().slice(0, 10); };
const dateLabel = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";
const rolesInScope = ["user", "builder", "builder_staff", "agent"];

const Card = ({ icon, label, value, note, tone = "emerald" }) => { const styles = { emerald: "bg-emerald-50 text-emerald-600", blue: "bg-blue-50 text-blue-600", violet: "bg-violet-50 text-violet-600", amber: "bg-amber-50 text-amber-600", rose: "bg-rose-50 text-rose-600" }; return <article className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-[9px] font-bold uppercase tracking-wide text-slate-400">{label}</p><strong className="mt-1 block text-2xl leading-7 text-slate-950">{fmt(value)}</strong><p className="mt-1 text-[9px] text-slate-500">{note}</p></div><span className={`grid h-9 w-9 place-items-center rounded-lg ${styles[tone]}`}>{createElement(icon, { size: 17 })}</span></div></article>; };
const Panel = ({ title, subtitle, action, children, className = "" }) => <section className={`overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm ${className}`}><header className="flex min-h-12 items-center justify-between border-b border-slate-100 px-4 py-2"><div><h2 className="text-[12px] font-black text-slate-800">{title}</h2>{subtitle && <p className="text-[8px] text-slate-400">{subtitle}</p>}</div>{action}</header>{children}</section>;

export default function LeadCaptureAnalytics() {
  const [data, setData] = useState({ users: [], leads: [], summary: {}, projects: {}, properties: {} });
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ search: "", role: "", state: "", city: "", from: "", to: "" });
  const load = async () => {
    setLoading(true);
    try {
      const [usersResult, leadResult, projectResult, propertyResult] = await Promise.allSettled([getAllUsers(), apiClient.get("/api/properties/leads/admin/overview", { params: { limit: 500 } }), getAllProjectsAnalytics(), getAllPropertiesAnalytics()]);
      const usersPayload = usersResult.status === "fulfilled" ? usersResult.value?.data : [];
      const leadPayload = leadResult.status === "fulfilled" ? leadResult.value?.data?.data || {} : {};
      setData({ users: (Array.isArray(usersPayload) ? usersPayload : usersPayload?.users || []).filter((user) => rolesInScope.includes(user.roleName)), leads: leadPayload.leads || [], summary: leadPayload.summary || {}, projects: projectResult.status === "fulfilled" ? projectResult.value?.data?.data || {} : {}, properties: propertyResult.status === "fulfilled" ? propertyResult.value?.data?.data || {} : {} });
    } finally { setLoading(false); }
  };
  useEffect(() => {
    // Initial synchronization with the existing admin APIs.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    load();
  }, []);

  const states = useMemo(() => [...new Set(data.users.map((user) => user.state).filter(valid))].sort(), [data.users]);
  const cities = useMemo(() => [...new Set(data.users.filter((user) => !filters.state || user.state === filters.state).map((user) => user.city).filter(valid))].sort(), [data.users, filters.state]);
  const users = useMemo(() => { const query = filters.search.trim().toLowerCase(); return data.users.filter((user) => (!filters.role || user.roleName === filters.role) && (!filters.state || user.state === filters.state) && (!filters.city || user.city === filters.city) && (!filters.from || new Date(user.createdAt) >= new Date(`${filters.from}T00:00:00`)) && (!filters.to || new Date(user.createdAt) <= new Date(`${filters.to}T23:59:59`)) && (!query || [user.name, user.email, user.phone, user.userCode, user.state, user.city, user.locality].some((value) => String(value || "").toLowerCase().includes(query)))); }, [data.users, filters]);
  const active = users.filter((user) => user.accountStatus === "active" && user.isActive !== false).length;
  const today = new Date().toISOString().slice(0, 10);
  const newToday = users.filter((user) => dayKey(user.createdAt) === today).length;
  const roleRows = useMemo(() => rolesInScope.map((role) => ({ name: clean(role), total: users.filter((user) => user.roleName === role).length })), [users]);
  const locationRows = useMemo(() => { const map = new Map(); users.forEach((user) => { const name = [user.city, user.state].filter(valid).join(", ") || "Not specified"; const row = map.get(name) || { name, total: 0, active: 0 }; row.total += 1; if (user.accountStatus === "active" && user.isActive !== false) row.active += 1; map.set(name, row); }); return [...map.values()].sort((a,b) => b.total-a.total).slice(0,8); }, [users]);
  const trend = useMemo(() => { const map = new Map(); users.forEach((user) => { const key = dayKey(user.createdAt); if (!key) return; const row = map.get(key) || { date: key, registrations: 0, leads: 0 }; row.registrations += 1; map.set(key,row); }); (data.summary?.dailyTrend || []).forEach((item) => { const row = map.get(item.date) || { date: item.date, registrations: 0, leads: 0 }; row.leads += Number(item.leads || 0); map.set(item.date,row); }); return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-30).map((row)=>({ ...row, label: new Date(`${row.date}T00:00:00`).toLocaleDateString("en-IN", { day:"2-digit", month:"short" }) })); }, [data.summary, users]);
  const recent = [...users].sort((a,b) => new Date(b.updatedAt || b.createdAt || 0) - new Date(a.updatedAt || a.createdAt || 0)).slice(0,10);
  const update = (key) => (event) => setFilters((current) => ({ ...current, [key]: event.target.value, ...(key === "state" ? { city: "" } : {}) }));

  return <div className="space-y-3 pb-5 text-slate-900">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black tracking-tight">Lead Capture & Activity Intelligence</h1><p className="text-[10px] text-slate-500">Role, location, onboarding, inventory and lead-journey visibility across customers and channel partners.</p></div><div className="flex gap-2"><button onClick={() => window.print()} className="flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-[9px] font-bold text-slate-600"><Download size={13}/>Export view</button><button onClick={load} className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-600 text-white"><RefreshCw size={14} className={loading ? "animate-spin" : ""}/></button></div></header>
    <div className="grid grid-cols-8 gap-2 rounded-xl border border-slate-200 bg-white p-2 shadow-sm"><label className="relative col-span-2"><Search size={13} className="absolute left-3 top-2.5 text-slate-400"/><input value={filters.search} onChange={update("search")} placeholder="Search name, phone, email, code or location" className="h-8 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-[9px] outline-none focus:border-emerald-500"/></label><select value={filters.role} onChange={update("role")} className="h-8 rounded-lg border border-slate-200 px-2 text-[9px]"><option value="">All roles</option>{rolesInScope.map((role)=><option key={role} value={role}>{clean(role)}</option>)}</select><select value={filters.state} onChange={update("state")} className="h-8 rounded-lg border border-slate-200 px-2 text-[9px]"><option value="">All states</option>{states.map((state)=><option key={state}>{state}</option>)}</select><select value={filters.city} onChange={update("city")} className="h-8 rounded-lg border border-slate-200 px-2 text-[9px]"><option value="">All cities</option>{cities.map((city)=><option key={city}>{city}</option>)}</select><input type="date" value={filters.from} onChange={update("from")} className="h-8 rounded-lg border border-slate-200 px-2 text-[9px]"/><input type="date" value={filters.to} onChange={update("to")} className="h-8 rounded-lg border border-slate-200 px-2 text-[9px]"/><button onClick={() => setFilters({ search:"",role:"",state:"",city:"",from:"",to:"" })} className="flex h-8 items-center justify-center gap-1 rounded-lg bg-slate-900 text-[9px] font-bold text-white"><Filter size={12}/>Clear filters</button></div>
    <section className="grid grid-cols-2 gap-2 lg:grid-cols-6"><Card icon={Users} label="People in scope" value={users.length} note="Users and channel partners"/><Card icon={UserCheck} label="Active accounts" value={active} note={`${users.length ? Math.round(active/users.length*100) : 0}% activation`} tone="blue"/><Card icon={CalendarDays} label="Joined today" value={newToday} note="New registrations" tone="violet"/><Card icon={Activity} label="Captured leads" value={data.summary?.total || data.leads.length} note="Live lead repository" tone="amber"/><Card icon={Building2} label="Projects" value={data.projects?.overview?.totalProjects} note="Published project inventory"/><Card icon={MapPin} label="Properties" value={data.properties?.overview?.totalProperties} note="Property inventory" tone="rose"/></section>
    <section className="grid grid-cols-12 gap-3"><Panel title="Acquisition & lead trend" subtitle="Registrations compared with captured lead volume" className="col-span-12 xl:col-span-6"><div className="h-56 p-2"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="label" tick={{fontSize:8}}/><YAxis tick={{fontSize:8}} allowDecimals={false}/><Tooltip/><Area dataKey="registrations" name="Registrations" stroke="#10b981" fill="#d1fae5"/><Area dataKey="leads" name="Leads" stroke="#3b82f6" fill="#dbeafe"/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Role composition" subtitle="Users, builders, builder staff and agents" className="col-span-12 xl:col-span-3"><div className="h-56 p-2"><ResponsiveContainer width="100%" height="100%"><BarChart data={roleRows} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" tick={{fontSize:8}}/><YAxis type="category" dataKey="name" width={72} tick={{fontSize:8}}/><Tooltip/><Bar dataKey="total" fill="#10b981" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Tracking coverage" subtitle="Verified signals currently available" className="col-span-12 xl:col-span-3"><div className="space-y-1.5 p-3">{[["Identity & role",true],["Work location",true],["Account/onboarding state",true],["Listings & projects",true],["Lead stages",true],["Session duration",false],["Page/click activity",false],["Clock-in / clock-out",false]].map(([label, available])=><div key={label} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-1.5 text-[9px]"><span>{label}</span><span className={`rounded-full px-2 py-0.5 font-bold ${available ? "bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{available ? "Live":"Collector needed"}</span></div>)}</div></Panel></section>
    <section className="grid grid-cols-12 gap-3"><Panel title="Location intelligence" subtitle="Account volume and activation by work location" className="col-span-12 xl:col-span-5"><div className="max-h-64 overflow-auto"><table className="w-full text-left text-[9px]"><thead className="sticky top-0 bg-slate-50 text-slate-400"><tr><th className="px-4 py-2">Location</th><th>Total</th><th>Active</th><th>Activation</th></tr></thead><tbody>{locationRows.map((row)=><tr key={row.name} className="border-t border-slate-100"><td className="px-4 py-2.5 font-bold">{row.name}</td><td>{row.total}</td><td>{row.active}</td><td className="font-bold text-emerald-600">{row.total ? Math.round(row.active/row.total*100):0}%</td></tr>)}</tbody></table></div></Panel><Panel title="Recent people activity" subtitle="Latest verified account or onboarding updates" className="col-span-12 xl:col-span-7"><div className="max-h-64 overflow-auto"><table className="w-full min-w-[680px] text-left text-[9px]"><thead className="sticky top-0 bg-slate-50 text-slate-400"><tr><th className="px-4 py-2">Person</th><th>Role</th><th>Location</th><th>Account state</th><th>Joined</th><th>Last recorded change</th><th></th></tr></thead><tbody>{recent.map((user)=><tr key={user._id} className="border-t border-slate-100 hover:bg-emerald-50/40"><td className="px-4 py-2.5"><strong className="block text-slate-800">{user.name || "Unnamed"}</strong><span className="text-slate-400">{user.email || user.phone || user.userCode}</span></td><td><span className="rounded-full bg-violet-50 px-2 py-1 font-bold text-violet-700">{clean(user.roleName)}</span></td><td>{[user.locality,user.city,user.state].filter(valid).join(", ") || "—"}</td><td><span className={`rounded-full px-2 py-1 font-bold ${user.accountStatus === "active" ? "bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{clean(user.accountStatus)}</span></td><td>{dateLabel(user.createdAt)}</td><td>{dateLabel(user.updatedAt || user.createdAt)}</td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></div></Panel></section>
    <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-[9px] text-blue-800"><strong>Privacy-safe tracking:</strong> this view uses operational records already stored by Propenu. Session timing, clickstream, and page-level behavior will appear only after an explicit consent-aware event collection API is implemented.</div>
  </div>;
}
